
//----------------------------------------------------
// The following code was generated by CUP v0.11b ${cupversion} (SVN rev )
//----------------------------------------------------

package whg.bcode;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SEMICOLON = 4;
  public static final int RBRACE = 3;
  public static final int IDENTIFIER = 17;
  public static final int AT = 7;
  public static final int LBRACKET = 5;
  public static final int COLON = 10;
  public static final int LBRACE = 2;
  public static final int RBRACKET = 6;
  public static final int AST = 12;
  public static final int STRING = 18;
  public static final int COMMA = 13;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int U4 = 14;
  public static final int U2 = 15;
  public static final int EXTENDS = 9;
  public static final int U1 = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "LBRACKET",
  "RBRACKET",
  "AT",
  "MINUS",
  "EXTENDS",
  "COLON",
  "EQ",
  "AST",
  "COMMA",
  "U4",
  "U2",
  "U1",
  "IDENTIFIER",
  "STRING",
  "NUMBER"
  };
}

